on: [push]

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        name: A job to say hello
        steps:
            - uses: actions/checkout@v4
            - id: foo
              uses: Michael-Davis76/Exercise1@f67de5aba4d831346c2b2cc902e09a053a945cab
              with:
                who-to-greet: 'Mona the Octocat'
            - run: echo random-number "$RANDOM_NUMBER"
              shell: bash
              env:
                RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}